{{- $secretName := include "hyperpod-ray-endpoint-operator.resourceName" (dict "suffix" "extensionapi-jwt-secret" "context" $) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $existingSecret }}
apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app: extensionapi-jwt
    component: security
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
